#!/usr/bin/env python3
"""bodymap.py — turns the app's muscle drawing into data the kit can draw.

    python3 Content/motion/tools/bodymap.py            write Content/motion/kit/bodymap.js
    python3 Content/motion/tools/bodymap.py --check    exit 1 if bodymap.js is out of date (kit_check runs this)

The source is .claude/skills/image/bodymap/bodymap.json: the traced front and back drawing the athlete app shows in
"Muscles worked" (one path per muscle group, the same muscle names as the Spine). It is never edited here. This script copies
it into one JS file and works out, for every muscle, where each of its shapes sits (centre and box), so a label can be joined
to the right place. The paths use only M, l and z, so no path library is needed.
"""
import hashlib, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / '.claude' / 'skills' / 'image' / 'bodymap' / 'bodymap.json'
OUT = ROOT / 'Content' / 'motion' / 'kit' / 'bodymap.js'
NUM = re.compile(r'-?\d+(?:\.\d+)?')


def shapes(d):
    """The closed shapes of a path made of M x y, relative l pairs and z."""
    out = []
    for chunk in re.split(r'(?=M)', d):
        if not chunk.startswith('M'):
            continue
        n = [float(x) for x in NUM.findall(chunk)]
        x, y = n[0], n[1]
        pts = [(x, y)]
        for i in range(2, len(n) - 1, 2):
            x += n[i]; y += n[i + 1]; pts.append((x, y))
        out.append(pts)
    return out


def describe(d):
    parts = []
    for pts in shapes(d):
        a = 0.0; cx = 0.0; cy = 0.0
        for i in range(len(pts)):
            x0, y0 = pts[i]; x1, y1 = pts[(i + 1) % len(pts)]
            c = x0 * y1 - x1 * y0
            a += c; cx += (x0 + x1) * c; cy += (y0 + y1) * c
        a /= 2
        if abs(a) < 1:
            continue
        xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
        parts.append({'cx': round(cx / (6 * a), 1), 'cy': round(cy / (6 * a), 1), 'area': round(abs(a)), 'x0': round(min(xs)), 'y0': round(min(ys)), 'x1': round(max(xs)), 'y1': round(max(ys))})
    parts.sort(key=lambda p: -p['area'])
    return parts


def build():
    raw = SRC.read_bytes()
    d = json.loads(raw)
    meta = {v: {k: describe(s) for k, s in d['groups'][v].items()} for v in ('front', 'back')}
    data = {'viewBox': d['viewBox'], 'place': d['place'], 'groups': d['groups'], 'line': d['line'], 'sil': d['sil'], 'parts': meta}
    sha = hashlib.sha1(raw).hexdigest()[:12]
    js = ('/* bodymap.js: GENERATED by tools/bodymap.py from .claude/skills/image/bodymap/bodymap.json. Do not edit.\n'
          ' * The athlete app\'s muscle drawing, front and back. KIT.bodymap.groups[view][muscle] is a path; parts[view][muscle] lists its shapes with\n'
          ' * their centres and boxes. source ' + sha + ' */\n'
          '(function (g) { g.KIT.bodymap = ' + json.dumps(data, separators=(',', ':')) + '; KIT.bodymap.source = "' + sha + '"; })(window);\n').replace('KIT.bodymap.source', 'g.KIT.bodymap.source')
    return js


def main():
    js = build()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != js:
            print('bodymap.js is out of date: run python3 Content/motion/tools/bodymap.py')
            return 1
        print('bodymap.js is up to date')
        return 0
    OUT.write_text(js, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({len(js) // 1024} KB)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
