#!/usr/bin/env node
/* kit_docs.js — writes Content/motion/kit/PIECES.md: every piece, alias and scene change in the kit, how to call it, and what each knob does.
 *
 *   node Content/motion/tools/kit_docs.js            write kit/PIECES.md
 *   node Content/motion/tools/kit_docs.js --check    exit 1 if PIECES.md is out of date
 *
 * The text comes from the kit itself (KIT.describe: the doc line and one line per param) and from catalog.json (the Menu number and name),
 * so it can never disagree with the code. Read it before you call a piece.
 */
'use strict';
const fs = require('fs'), path = require('path');
let chromium;
try { ({ chromium } = require('playwright')); } catch (e) { ({ chromium } = require('/opt/node22/lib/node_modules/playwright')); }
const { serve } = require('./serve');
const MOTION = path.resolve(__dirname, '..'), OUT = path.join(MOTION, 'kit', 'PIECES.md');

(async () => {
  const cat = JSON.parse(fs.readFileSync(path.join(MOTION, 'catalog.json'), 'utf8')), nums = JSON.parse(fs.readFileSync(path.join(MOTION, 'numbers.json'), 'utf8')).numbers;
  const srv = await serve(), port = srv.address().port;
  const exe = process.env.CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
  const browser = await chromium.launch({ executablePath: fs.existsSync(exe) ? exe : undefined, args: ['--no-sandbox'] });
  const pg = await browser.newPage();
  await pg.goto(`http://127.0.0.1:${port}/motion/lab.html?render=1`);
  await pg.waitForFunction('window.REEL_READY === true', null, { timeout: 120000 });
  const data = await pg.evaluate(() => {
    const KIT = window.KIT, show = v => { try { const s = JSON.stringify(v, (k, x) => (typeof x === 'function' ? '(a function of time)' : x)); return s === undefined ? 'null' : s; } catch (e) { return '?'; } };
    const out = [];
    for (const id of KIT.ids()) {
      const d = KIT.describe(id), real = KIT.defs[id].kind === 'alias' ? null : KIT.defs[id];
      out.push({ id, kind: d.kind, base: d.base, doc: d.doc, group: d.group, cues: d.cues, params: Object.keys(d.params).map(k => ({ k, def: show(d.params[k].default), doc: d.params[k].doc })), preset: KIT.defs[id].kind === 'alias' ? show(KIT.defs[id].preset) : null, real: !!real });
    }
    const dataItems = {};
    for (const [kind, o] of Object.entries(KIT.data)) dataItems[kind] = Object.values(o).map(v => ({ id: v.id, doc: v.doc || '' }));
    return { defs: out, dataItems };
  });
  await browser.close(); srv.close();

  const byId = Object.fromEntries(cat.items.map(i => [i.id, i])), gname = Object.fromEntries(cat.groups.map(g => [g.id, g.name]));
  const order = cat.groups.map(g => g.id);
  const L = [];
  L.push('# The kit: every piece, how to call it, what its knobs do', '',
    '> Generated by `tools/kit_docs.js` from the kit itself. Do not edit by hand: change the piece\'s `doc` and `params`, then run the tool.', '',
    'Call a piece with `KIT.draw(id, ctx, t, params)`; a scene change with `KIT.transition(id, params)` or `KIT.cut(id, ctx, A, B, p, params)`; a look with `KIT.use(id)`.',
    'A param you leave out takes the default shown. `at` is always a time in seconds; positions are canvas pixels. See `README.md` for the conventions.', '');
  const groups = {};
  for (const d of data.defs) (groups[d.group || 'other'] = groups[d.group || 'other'] || []).push(d);
  const names = Object.keys(groups).sort((a, b) => (order.indexOf(a) < 0 ? 99 : order.indexOf(a)) - (order.indexOf(b) < 0 ? 99 : order.indexOf(b)));
  for (const g of names) {
    L.push(`## ${gname[g] || g}`, '');
    for (const d of groups[g]) {
      const it = byId[d.id], no = it ? ` (Menu #${nums[d.id]})` : '';
      L.push(`### ${it ? it.name : d.id} — \`${d.id}\`${no}`, '', d.doc, '');
      L.push(d.kind === 'join' ? `Scene change. \`KIT.transition('${d.id}', { ... })\`` : d.kind === 'alias' ? `A preset of \`${d.base}\`: \`KIT.draw('${d.id}', ctx, t, { ... })\`. Preset: \`${d.preset}\`` : `\`KIT.draw('${d.id}', ctx, t, { ... })\``, '');
      if (d.params.length) {
        L.push('| param | default | what it does |', '|---|---|---|');
        for (const p of d.params) L.push(`| \`${p.k}\` | \`${p.def.replace(/\|/g, '\\|').slice(0, 90)}\` | ${p.doc.replace(/\|/g, '\\|')} |`);
        L.push('');
      }
    }
  }
  L.push('## Data: looks, type pairs, feel, house rules, finish settings', '');
  for (const [kind, arr] of Object.entries(data.dataItems)) {
    if (!arr.length) continue;
    L.push(`**${kind}**`, '');
    for (const v of arr) { const it = byId[v.id]; L.push(`- \`${v.id}\`${it ? ` (#${nums[v.id]} ${it.name})` : ''}: ${v.doc}`); }
    L.push('');
  }
  const text = L.join('\n') + '\n';
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== text) { console.log('kit/PIECES.md is out of date: run node Content/motion/tools/kit_docs.js'); process.exit(1); }
    console.log('kit/PIECES.md is up to date'); return;
  }
  fs.writeFileSync(OUT, text); console.log(`wrote kit/PIECES.md (${data.defs.length} entries, ${Math.round(text.length / 1024)} KB)`);
})().catch(e => { console.error(e); process.exit(1); });
