"""Download the English site fonts (Barlow, Barlow Condensed, JetBrains Mono, DM Sans) from Google Fonts
into assets/fonts/ and write assets/css/fonts.css, so the pages stop asking Google for them
(website audit package 6c, Amir's yes 2026-10-02).

Latin subset only. All four families are SIL Open Font License 1.1.
Re-run this only to change the weights; the files are committed.
    python scripts/site_audit/fetch_fonts.py
"""
import os, re, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FONTS = os.path.join(ROOT, 'assets', 'fonts')
CSS_OUT = os.path.join(ROOT, 'assets', 'css', 'fonts.css')
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'

API = ('https://fonts.googleapis.com/css2'
       '?family=Barlow+Condensed:wght@300;400;500;600;700;800;900'
       '&family=Barlow:wght@300;400;500;600;700;800;900'
       '&family=JetBrains+Mono:wght@400;500;700'
       '&family=DM+Sans:wght@300;400;500;600;700'
       '&display=swap')


def get(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    return urllib.request.urlopen(req, timeout=30).read()


def main():
    css = get(API).decode('utf-8')
    blocks = re.findall(r'/\* (\S+) \*/\s*(@font-face \{.*?\})', css, re.S)
    out = ['/* Self-hosted English fonts (SIL Open Font License 1.1: see /assets/fonts/LICENSES.txt).',
           '   Latin subset only. Generated by scripts/site_audit/fetch_fonts.py: do not hand-edit. */']
    seen = {}
    # Variable families (JetBrains Mono, DM Sans) answer every weight with the same file: one rule per file
    # with the weight range, not one per weight.
    weights = {}
    for subset, block in blocks:
        if subset == 'latin':
            url = re.search(r'url\((https://[^)]+)\)', block).group(1)
            weights.setdefault(url, []).append(int(re.search(r'font-weight: (\d+);', block).group(1)))
    for subset, block in blocks:
        if subset != 'latin':
            continue
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)
        if url in seen:
            continue
        ws = weights[url]
        if len(ws) > 1:
            wt, tag = '%d %d' % (min(ws), max(ws)), 'Variable'
        else:
            wt = tag = str(ws[0])
        name = '%s-%s.woff2' % (fam.replace(' ', ''), tag)
        seen[url] = name
        path = os.path.join(FONTS, name)
        if not os.path.exists(path):
            data = get(url)
            open(path, 'wb').write(data)
            print('downloaded', name, len(data))
        rule = ("@font-face{font-family:'%s';font-style:normal;font-weight:%s;font-display:swap;"
                "src:url('/assets/fonts/%s') format('woff2');"
                "unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,"
                "U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;}"
                % (fam, wt, name))
        out.append(rule)
    open(CSS_OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    total = sum(os.path.getsize(os.path.join(FONTS, n)) for n in seen.values())
    print('%d files, %d KB, wrote %s' % (len(seen), total // 1024, CSS_OUT))


if __name__ == '__main__':
    main()
